name: UnPure
author: Zohiu
description: Infected vs. Humans
version: '1.0'
main: de.zohiu.unpure.UnPure
api-version: '1.21'
commands:
  loadmap:
    usage: /loadmap
  unloadmap:
    usage: /unloadmap
  gotomap:
    usage: /gotomap
  start:
    usage: /start
  createtemplate:
    usage: /createtemplate